title: Kati Kloppenborg - Portfolio
description: ""
url: "https://katikloppenb.org"
baseurl: "/portfolio"
author:
  name: "Kati Kloppenborg"
  email: "ka.kloppenborg@gmail.com"
collections:
  paintings:
    output: true   # Ensure the pages for each painting are generated
    permalink: /paintings/:name/
markdown: kramdown
